@startuml
'https://plantuml.com/sequence-diagram

hide footbox
scale 2
skinparam MaxMessageSize 150

actor User
participant ":SudoCook" as SudoCook
participant ":Parser" as Parser
participant "cmd:CookCommand" as Cmd
participant "recipes:RecipeBook" as RecipeBook
participant "inventory:Inventory" as Inventory
participant ":Ui" as Ui

User -> SudoCook : enter cook command
activate SudoCook

SudoCook -> Parser : parse(input)
activate Parser

create Cmd
Parser -> Cmd ** : CookCommand(false, index)
activate Cmd
Cmd --> Parser
deactivate Cmd

Parser --> SudoCook : cmd
deactivate Parser

SudoCook -> RecipeBook : getRecipe(index)
activate RecipeBook
alt index out of bounds
    RecipeBook -> Ui : Print Error
    activate Ui
    Ui --> RecipeBook
    deactivate Ui
    RecipeBook --> SudoCook : null
else recipe found
    RecipeBook --> SudoCook : recipe
end
deactivate RecipeBook

SudoCook -> Cmd : execute(recipe, inventory)
activate Cmd

alt recipe == null
    Cmd --> SudoCook
else recipe exists
    Cmd -> Inventory : findIndexByName(name)
    activate Inventory
    Inventory --> Cmd
    deactivate Inventory

    Cmd -> Inventory : getIngredient(index).getQuantity()
    activate Inventory
    Inventory --> Cmd
    deactivate Inventory

    alt ingredients available
        Cmd -> Inventory : updateQuantity(...) / removeIngredient(...)
        activate Inventory
        Inventory --> Cmd
        deactivate Inventory

        Cmd -> Ui : printMessage(...)
        activate Ui
        Ui --> Cmd
        deactivate Ui
    else ingredients missing
        Cmd -> Ui : printError(...)
        activate Ui
        Ui --> Cmd
        deactivate Ui
    end
end

SudoCook <-- Cmd
deactivate Cmd
destroy Cmd

SudoCook --> User
deactivate SudoCook

@enduml
