@startuml
'https://plantuml.com/sequence-diagram

scale 4
autonumber
hide footbox

skinparam MaxMessageSize 150

actor User
participant ":SudoCook" as SudoCook
participant ":Parser" as Parser
participant "cmd:RecommendByMissingCommand" as Cmd
participant "inventory:Inventory" as Inventory
participant "item:Ingredient" as Item
participant "recipes:RecipeBook" as RecipeBook
participant "recipe:Recipe" as Recipe
participant ":Ui" as Ui

User -> SudoCook : run()
activate SudoCook

SudoCook -> Parser : parse("recommend-r missing/2")
activate Parser

create Cmd
Parser -> Cmd ** :RecommendByMissingCommand(2)
activate Cmd
Cmd --> Parser
deactivate Cmd

Parser --> SudoCook : cmd:RecommendByMissingCommand
deactivate Parser

SudoCook -> Cmd : execute(inventory, recipes)
activate Cmd

loop for each recipe in recipes
    Cmd -> RecipeBook : getRecipe(i)
    activate RecipeBook
    RecipeBook --> Cmd : recipe
    deactivate RecipeBook

    Cmd -> Cmd : getMissingIngredients(recipe, inventory)
    activate Cmd

    Cmd -> Recipe : getIngredients()
    activate Recipe
    Recipe --> Cmd : requiredIngredients
    deactivate Recipe

    loop for each required ingredient in recipe
        Cmd -> Inventory : getIngredient(j)
        activate Inventory
        Inventory --> Cmd : item
        deactivate Inventory
        opt item name matches required ingredient
            Cmd -> Item : getQuantity()
            activate Item
            Item --> Cmd : available
            deactivate Item
        end
    end
    opt available < required.getQuantity()
        note right of Cmd : add to missing list
    end

    Cmd --> Cmd : missing
    deactivate Cmd

    opt 0 < missing.size() <= maxMissing
        Cmd -> Recipe : getName()
        activate Recipe
        Recipe --> Cmd : recipeName
        deactivate Recipe
        note right of Cmd : append recipeName + missing to resultList (sb)
    end
end

Cmd -> Ui : printMessage(resultString)
activate Ui
Ui --> Cmd
deactivate Ui

SudoCook <-- Cmd
deactivate Cmd
destroy Cmd

SudoCook --> User
deactivate SudoCook

@enduml
