@startuml
'https://plantuml.com/sequence-diagram

scale 4
autonumber
hide footbox

skinparam MaxMessageSize 150

actor User
participant ":SudoCook" as SudoCook
participant ":Parser" as Parser
participant "cmd:RecommendByIngredientCommand" as Cmd
participant "inventory:Inventory" as Inventory
participant "ingredient:Ingredient" as Ingredient
participant "recipes:RecipeBook" as RecipeBook
participant "recipe:Recipe" as Recipe
participant ":Ui" as Ui

User -> SudoCook : run()
activate SudoCook

SudoCook -> Parser : parse("recommend-r n/beef")
activate Parser

create Cmd
Parser -> Cmd ** :RecommendByIngredientCommand("beef")
activate Cmd
Cmd --> Parser
deactivate Cmd

Parser --> SudoCook : cmd:RecommendByIngredientCommand
deactivate Parser

SudoCook -> Cmd : execute(inventory, recipes)
activate Cmd

loop for each ingredient in inventory
    Cmd -> Inventory : getIngredient(i)
    activate Inventory
    Inventory --> Cmd : ingredient
    deactivate Inventory
    opt ingredient name matches
        Cmd -> Ingredient : getQuantity()
        activate Ingredient
        Ingredient --> Cmd : amount
        deactivate Ingredient
    end
end

loop for each recipe in recipes
    Cmd -> RecipeBook : getRecipe(i)
    activate RecipeBook
    RecipeBook --> Cmd : recipe
    deactivate RecipeBook

    Cmd -> Recipe : getIngredients()
    activate Recipe
    Recipe --> Cmd : ingredientList
    deactivate Recipe

    loop for each ingredient in ingredientList
        opt ingredient name matches AND quantity <= amount
            Cmd -> Recipe : getName()
            activate Recipe
            Recipe --> Cmd : recipeName
            deactivate Recipe
            note right of Cmd : append recipeName to resultList (sb)
        end
    end
end

Cmd -> Ui : printMessage(resultString)
activate Ui
Ui --> Cmd
deactivate Ui

SudoCook <-- Cmd
deactivate Cmd
destroy Cmd

SudoCook --> User
deactivate SudoCook

@enduml